ERROR 2023-10-07 14:14:59,272 [log:241] Internal Server Error: /api/v1/comment/student/1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'Teacher' object has no attribute 'is_authenticated'
ERROR 2023-10-07 14:18:29,948 [log:241] Internal Server Error: /api/v1/comment/student/1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'Teacher' object has no attribute 'is_authenticated'
ERROR 2023-10-07 14:18:49,874 [log:241] Internal Server Error: /api/v1/comment/student/1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'Teacher' object has no attribute 'is_authenticated'
ERROR 2023-10-07 14:22:13,294 [log:241] Internal Server Error: /api/v1/comment/student/1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'Teacher' object has no attribute 'is_authenticated'
ERROR 2023-10-07 14:23:25,846 [log:241] Internal Server Error: /api/v1/comment/student/1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'Teacher' object has no attribute 'is_authenticated'
ERROR 2023-10-07 14:23:43,632 [log:241] Internal Server Error: /api/v1/comment/student/1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'Teacher' object has no attribute 'is_authenticated'
ERROR 2023-10-07 14:26:28,185 [log:241] Internal Server Error: /api/v1/comment/student/1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'Teacher' object has no attribute 'is_authenticated'
ERROR 2023-10-07 15:03:22,880 [main:574] Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/mixer/main.py", line 568, in blend
    return type_mixer.blend(**values)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/mixer/main.py", line 140, in blend
    target = self.postprocess(target, postprocess_values)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/mixer/backend/django.py", line 179, in postprocess
    target = self.__mixer.postprocess(target)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/mixer/backend/django.py", line 429, in postprocess
    target.save()
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/husan/Desktop/project-beta/apps/authentication/signals.py", line 85, in auto_create_attendance_and_lesson
    students = instance.group.students.filter(group=instance.group)
AttributeError: Mixer (<class 'apps.authentication.models.Lesson'>): 'NoneType' object has no attribute 'students'

ERROR 2023-10-07 15:03:46,212 [main:574] Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/mixer/main.py", line 568, in blend
    return type_mixer.blend(**values)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/mixer/main.py", line 140, in blend
    target = self.postprocess(target, postprocess_values)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/mixer/backend/django.py", line 179, in postprocess
    target = self.__mixer.postprocess(target)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/mixer/backend/django.py", line 429, in postprocess
    target.save()
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/husan/Desktop/project-beta/apps/authentication/signals.py", line 85, in auto_create_attendance_and_lesson
    students = instance.group.students.filter(group=instance.group)
AttributeError: Mixer (<class 'apps.authentication.models.Lesson'>): 'NoneType' object has no attribute 'students'

ERROR 2023-10-07 21:51:04,580 [log:241] Internal Server Error: /api/v1/lessons/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 337, in get
    return self.list(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:51:04,853 [log:241] Internal Server Error: /api/v1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 358, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:52:02,240 [log:241] Internal Server Error: /api/v1/lessons/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 337, in get
    return self.list(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:52:02,505 [log:241] Internal Server Error: /api/v1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 358, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:52:24,340 [log:241] Internal Server Error: /api/v1/lessons/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 337, in get
    return self.list(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:52:24,614 [log:241] Internal Server Error: /api/v1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 358, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:54:18,615 [log:241] Internal Server Error: /api/v1/lessons/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 337, in get
    return self.list(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:54:18,905 [log:241] Internal Server Error: /api/v1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 358, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:57:03,765 [log:241] Internal Server Error: /api/v1/lessons/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 337, in get
    return self.list(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:57:04,032 [log:241] Internal Server Error: /api/v1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 358, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:58:12,711 [log:241] Internal Server Error: /api/v1/lessons/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 337, in get
    return self.list(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-07 21:58:12,982 [log:241] Internal Server Error: /api/v1/lesson/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/apps/initialization/views.py", line 358, in get
    return self.retrieve(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/husan/Desktop/project-beta/apps/initialization/serializers.py", line 59, in get_group_data
    "teacher": obj.group.teacher.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
ERROR 2023-10-10 09:42:34,562 [log:241] Internal Server Error: /api/v1/comment/reply/parent/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 278, in get_permissions
    return [permission() for permission in self.permission_classes]
TypeError: 'BasePermissionMetaclass' object is not iterable
ERROR 2023-10-10 14:36:54,176 [log:241] Internal Server Error: /api/v1/comment/reply/parent/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'dict' object has no attribute 'is_authenticated'
ERROR 2023-10-10 14:37:16,665 [log:241] Internal Server Error: /api/v1/comment/reply/parent/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'dict' object has no attribute 'is_authenticated'
ERROR 2023-10-10 14:37:31,057 [log:241] Internal Server Error: /api/v1/comment/reply/parent/1/
Traceback (most recent call last):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/husan/Desktop/project-beta/.environment/lib/python3.10/site-packages/rest_framework/permissions.py", line 140, in has_permission
    return bool(request.user and request.user.is_authenticated)
AttributeError: 'Parent' object has no attribute 'is_authenticated'
